[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "autogen-agentchat"
version = "0.3.0dev0"
description = "AutoGen agent and group chat library"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["autogen-core",

]

[tool.uv]
dev-dependencies = []


[tool.ruff]
extend = "../../pyproject.toml"
include = ["src/**", "tests/*.py"]

[tool.pyright]
extend = "../../pyproject.toml"
include = ["src", "tests"]

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]

[tool.poe]
include = "../../shared_tasks.toml"

[tool.poe.tasks]
test = "pytest -n auto"
