# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: dotnet-ci

on:
  pull_request:
    branches: [ "dotnet" ] # todo: change it back to main when completed

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: dotnet/global.json
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./dotnet
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./dotnet
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./dotnet